name: Zig CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - run: zig fmt --check .
      - run: zig build test
